### ISSUE TITLE
Using C++ arrays (or vectors) instead of C-style arrays

### ISSUE THREAD

**Issue by kiarashgl** [roozbehsayadi/Minesweeper-AI-Agent#1]
Hi,
I think that you could use STL Vectors or arrays, instead of C-style arrays and handling the pointer stuff; for example in this line.
https://github.com/roozbehsayadi/Minesweeper-AI-Agent/blob/e0438ca721c0fe81244236ddb191bf7da730325f/Game/minesweeper.cpp#L9

**Comment by roozbehsayadi** [comment]
Hi
Thanks for your reply. You are right.
I just wanted to deal with pointers and manage memory myself to feel the pressure and confusion. :smile:
